GET http://localhost:2029/

################################################################

GET http://localhost:2029/Products

################################################################

POST  http://localhost:2029/Products
Content-Type: application/json

{
    "image":"https://i.postimg.cc/FzyzwFFS/1.jpg",
    "name":"YGYI",
    "description":"dtudrysht",
    "category":"hoodie",
    "price": "300"
}

################################################################

PUT http://localhost:2029/Products/62309ffa2f348b2e97fc0d08
Content-Type: application/json

{
 "image":"https://i.postimg.cc/FzyzwFFS/1.jpg",
    "name":"YGYI",
    "description":"dtudrysht",
    "category":"hoodie",
    "price": "500"
}

################################################################

GET http://localhost:2029/logout

################################################################



POST  http://localhost:2029/Clients
Content-Type: application/json

{
    "name": "Sima",
    "email": "sima@yahoo.com",
    "password":"0123456"
}

################################################################
