GET http://localhost:2029/

################################################################

GET http://localhost:2029/Products

################################################################

POST  http://localhost:2029/Products
Content-Type: application/json

{
    "image":"https://i.postimg.cc/FzyzwFFS/1.jpg",
    "name":"jhvads",
    "description":"dtudrysht",
    "category":"hoodie",
    "price": "300"
}

################################################################

PUT http://localhost:2029/Products/6231b40f75175833e10df690
Content-Type: application/json

{
 "image":"https://i.postimg.cc/FzyzwFFS/1.jpg",
    "name":"YGYI",
    "description":"dtudrysht",
    "category":"hoodie",
    "price": "500"
}

################################################################

GET http://localhost:2029/Clients/logout

################################################################



POST  http://localhost:2029/Clients/signup
Content-Type: application/json

{
    "name": "Sima",
    "email": "sima@yahoo.com",
    "password":"0123456",
    "phone_number": "0123456"
}

################################################################
GET http://localhost:2029/Clients
